# config/packages/workflow.yaml
framework:
    workflows:
        team_report_invoice_status:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'statusAsString'
            supports:
                - App\Entity\Invoice
            initial_marking: Draft
            places:
                - Draft
                - Sent
                - Paid
                - Cancelled
            transitions:
                Sent:
                    from: Draft
                    to: Sent
                    guard: "subject.isTeamReportInvoice()"

                Paid:
                    from: Sent
                    to: Paid
                    guard: "subject.isTeamReportInvoice()"

                Cancelled:
                    from:
                        - Draft
                    to: Cancelled
                    guard: "subject.isTeamReportInvoice()"

        report_status:
            type: state_machine

            audit_trail:
                enabled: true

            marking_store:
                type: method
                property: statusAsString

            supports:
                - App\Entity\Report

            initial_marking: Draft

            places:
                - Draft
                - Sent
                - Validated
                - Invalidated

            transitions:
                Send:
                    from:
                        - Draft
                        - Invalidated
                    to: Sent

                Validated:
                    from: Sent
                    to: Validated

                Invalidated:
                    from: Sent
                    to: Invalidated