payum:
    storages:
        App\Entity\Payment: { doctrine: orm }

    security:
        token_storage:
            App\Entity\PaymentToken: { doctrine: orm }

    gateways:
        offline:
            factory: offline

        stripe_checkout_session:
            factory: stripe_checkout_session
            publishable_key: '%env(string:STRIPE_PUBLISHABLE_KEY)%'
            secret_key: '%env(string:STRIPE_SECRET_KEY)%'
            webhook_secret_keys:
                - '%env(string:STRIPE_WEBHOOK_SECRET_KEY)%'
        
        stripe_js:
            factory: stripe_js
            publishable_key: '%env(string:STRIPE_PUBLISHABLE_KEY)%'
            secret_key: '%env(string:STRIPE_SECRET_KEY)%'
            webhook_secret_keys:
                - '%env(string:STRIPE_WEBHOOK_SECRET_KEY)%'