App\Entity\Power:
  type: entity
  repositoryClass: App\Repository\PowerRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    type:
        type: string
        columnDefinition: ENUM('Car', 'Cyclo')
    name:
        type: string   

