App\Entity\Report:
  type: entity
  repositoryClass: App\Repository\ReportRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    start:
        type: date
    end:
        type: date
    km:
        type: integer
        default: 0
    total:
        type: decimal
        precision: 8
        scale: 2
        nullable: false
    validated_at:
          type: datetime
          nullable: true
    validated_by:
          type: integer
          nullable: true
          unique: false
  manyToOne:
    user:
      targetEntity: App\Entity\User
      inversedBy: reports
      joinColumn:
        name: user_id
        referencedColumnName: id
    vehicule:
      targetEntity: App\Entity\Vehicule
      #inversedBy: reports
      joinColumn:
        name: vehicule_id
        referencedColumnName: id
    validator:
      targetEntity: App\Entity\User
      joinColumn:
        name: validated_by
        referencedColumnName: id
        onDelete: CASCADE
    scale:    
      targetEntity: App\Entity\Scale
      joinColumn:
        name: scale_id
        referencedColumnName: id    
  oneToMany:
    lines:
      orderBy: {'travel_date': 'ASC'}  
      targetEntity: App\Entity\ReportLine
      mappedBy: report
      cascade: [remove, persist]
      orphanRemoval: true
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue, calculateKm, calculateTotal ]
