App\Entity\Scale:
  type: entity
  repositoryClass: App\Repository\ScaleRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    year:
        type: string
        length: 4
    km_min:
        type: integer
    km_max:
        type: integer
        nullable: true
    rate:
        type: float
    amount:
        type: smallint
        options:
          default: 0
  manyToOne:
    power:
      targetEntity: App\Entity\Power
      joinColumn:
        name: power_id
        referencedColumnName: id          